// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCluIM32iPCm3X0oKqA-o5sa06K5lbRNDc',
    appId: '1:739878273878:web:3b6367b25b54a5f7204cf7',
    messagingSenderId: '739878273878',
    projectId: 'flutter-firebase-34d4d',
    authDomain: 'flutter-firebase-34d4d.firebaseapp.com',
    databaseURL: 'https://flutter-firebase-34d4d-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebase-34d4d.firebasestorage.app',
    measurementId: 'G-XZ6X159CY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTPdPliM0zYSmSAYEaOX6OwPYCoCBd_Yc',
    appId: '1:739878273878:android:dd64cbbc9d2f5eab204cf7',
    messagingSenderId: '739878273878',
    projectId: 'flutter-firebase-34d4d',
    databaseURL: 'https://flutter-firebase-34d4d-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebase-34d4d.firebasestorage.app',
  );
}
